### ISSUE TITLE
Vamos simular um painel de Leis? Ou somente a randomização de leis?

### ISSUE THREAD

**Issue by LisboaAnt** [LisboaAnt/randomcountrylaws#2]

**Comment by LisboaAnt** [comment]
Pois se for apenas o aleatório ficaria estranho e como já temos o sistema podemos fazer os dois @Jussivan, o que acha?

**Comment by Jussivan** [comment]
Olá @LisboaAnt, creio que sua ideia acrescentaria uma boa funcionalidade ao sistema, ampliando a variedade de utilidades do mesmo para os usuários.
